name: Riffl example application
properties:
  catalog.name: glue
  s3.bucket: <S3 bucket>
execution:
  type: FLINK
  configuration:
    jobmanager.memory.process.size: 2g
    taskmanager.memory.process.size: 10g
    taskmanager.numberOfTaskSlots: 4
    parallelism.default: 8
    execution.checkpointing.interval: 120s
    execution.checkpointing.mode: EXACTLY_ONCE
    state.savepoints.dir: s3p://${properties.s3.bucket}/state/savepoints
    state.checkpoints.dir: s3p://${properties.s3.bucket}/state/checkpoints
metrics:
  storeUri: s3://${properties.s3.bucket}/metrics/
catalogs:
  - create: " 
      CREATE CATALOG ${properties.catalog.name} WITH (
        'type'='iceberg',
        'warehouse'='s3a://${properties.s3.bucket}',
        'catalog-impl'='org.apache.iceberg.aws.glue.GlueCatalog',
        'io-impl'='org.apache.iceberg.aws.s3.S3FileIO',
        'format'='parquet',
        'parquet.compression'='zstd',
        'format-version'='2'
      )"
sources:
  - create: " 
      CREATE TABLE IF NOT EXISTS source_product (
          id BIGINT,
          type INT,
          name STRING,
          price DECIMAL(10, 2),
          buyer_name STRING, 
          buyer_address STRING  
      ) WITH (
          'connector' = 'datagen',
          'rows-per-second' = '500000',
          'fields.type.kind'='random',
          'fields.type.min'='1',
          'fields.type.max'='10',
          'fields.price.kind'='random',
          'fields.price.min'='10',
          'fields.price.max'='1000'
      )"
    map: "    
        SELECT 
          *,
          CURRENT_TIMESTAMP as ts,
          CAST(DATE_FORMAT(CURRENT_TIMESTAMP, 'yyyy-MM-dd') AS STRING) AS dt, 
          CAST(DATE_FORMAT(CURRENT_TIMESTAMP, 'HH') AS STRING) AS hr 
        FROM source_product 
        WHERE (type = 1 AND RAND_INTEGER(0,100) BETWEEN 0 AND 100)
           OR (type = 2 AND RAND_INTEGER(0,100) BETWEEN 0 AND 60)
           OR (type > 2 AND RAND_INTEGER(0,100) BETWEEN 0 AND 20)
        "
sinks:
  - table: "glue.riffl.product_optimized"
    query: "SELECT * FROM source_product"
    distribution:
      className: "io.riffl.sink.row.DistributeByFactory"
      properties:
        keys:
          - "type"
  - table: "glue.riffl.product_default"
    query: "SELECT * FROM source_product"
